version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mongodb://database:27017/mydatabase

  database:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  service:
    build: ./service
    depends_on:
      - database
    environment:
      - DATABASE_URL=mongodb://database:27017/mydatabase